kind 6 repost impl
damus-io/notedeck pull request #302
Opened 2024-09-13 19:09 UTC by kernelkind

2024-09-16 22:20 UTC, jb55 requested changes
A few comments!

2024-09-16 22:20 UTC, jb55 commented on src/ui/note/mod.rs
> +            if let Some(tag_str) = tag.get(0).unwrap().variant().str() {
```suggestion
            if let Some("e") = tag.get_unchecked(0).variant().str() {
```

2024-09-16 22:20 UTC, jb55 commented on src/ui/note/mod.rs
> +fn get_reposted_note_key(ndb: &Ndb, txn: &Transaction, note: &Note) -> Option<NoteKey> {
you can just return the note here

```suggestion
fn get_reposted_note<'a>(ndb: &Ndb, txn: &'a Transaction, note: &Note) -> Option<Note<'a>> {
```

2024-09-16 22:20 UTC, jb55 commented on src/ui/note/mod.rs
> +        for tag in note.tags().iter() {
```suggestion
        for tag in note.tags().iter() {
            if tag.count() == 0 {
	        continue;
            }
```

this is needed or we can crash on `unwrap` or `get_unchecked` with a malformed note, but maybe we should just do this so its safe even during refactors:

```rust
if let Some("e") = tag.get(0).and_then(|t|t.variant().str())
```

2024-09-17 17:13 UTC, kernelkind commented
rebased with master

2024-09-17 17:17 UTC, merged